// <auto-generated />
using ExpenseTracker.BusinessLogic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTracker.BusinessLogic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240414160742_AddValueToCodeValue")]
    partial class AddValueToCodeValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ExpenseTracker.BusinessLogic.DbSet.CodeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeValueClassificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CodeValueClassificationId");

                    b.ToTable("CodeValues");
                });

            modelBuilder.Entity("ExpenseTracker.BusinessLogic.DbSet.CodeValueClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("CodeValueClassifications");
                });

            modelBuilder.Entity("ExpenseTracker.BusinessLogic.DbSet.CodeValue", b =>
                {
                    b.HasOne("ExpenseTracker.BusinessLogic.DbSet.CodeValueClassification", "CodeValueClassification")
                        .WithMany("CodeValues")
                        .HasForeignKey("CodeValueClassificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeValueClassification");
                });

            modelBuilder.Entity("ExpenseTracker.BusinessLogic.DbSet.CodeValueClassification", b =>
                {
                    b.Navigation("CodeValues");
                });
#pragma warning restore 612, 618
        }
    }
}
